version: '3.8'

services:
  database:
    image: postgres:17
    container_name: teddy-open-finances-db
    restart: always
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - teddy_open_finances_network
    volumes:
      - teddy_open_finances_volume_db:/var/lib/postgresql/data

  api:
    build: .
    container_name: teddy-open-finances-api
    restart: always
    depends_on:
      - database
    environment:
      - "POSTGRES_HOST=database"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - 3000:3000
    networks:
      - teddy_open_finances_network
    volumes:
      - .:/usr/src/api
    command: ["npm", "run", "start:prod"]

networks:
  teddy_open_finances_network:
    driver: bridge

volumes:
  teddy_open_finances_volume_db:
  teddy_open_finances_volume_api:
